### ISSUE TITLE
gulp & sass

### ISSUE THREAD

**Issue by Haroenv** [bullgit/chitchat#18]
I don't think we use them, is it necessary to have them then?

(also seem to have come from the heroku, just as the `dist` folder)

**Comment by LukyVj** [comment]
I think we should use SASS now.

**Comment by Haroenv** [comment]
Not opposed, easier for maintainability, and the code lends itself to be nested.

**Comment by LukyVj** [comment]
At the beginning, we started with a simple vanilla project, now it get's "bigger" we def need gulp ! 

I'm currently implementing it on a new branch
