### ISSUE TITLE
node folder

### ISSUE THREAD

**Issue by Haroenv** [bullgit/chitchat#28]
This should be removed, but weirdly it's already in the `.gitignore`. I can try fixing once that branch is merged, that will be better I think.

**Comment by dervondenbergen** [comment]
this could be the solution: http://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore

**Comment by LukyVj** [comment]
We just have to keep the package.json and yes, get rid of the `node_modules`folder;
