### ISSUE TITLE
Scroll to new messages

### ISSUE THREAD

**Issue by Haroenv** [bullgit/chitchat#4]
like @dervondenbergen did on http://v2.bullchat.bullg.it

**Comment by LukyVj** [comment]
Yep, you can check I think the line is still here, we deployed the website really quickly.

But I'll fix it tonite

**Comment by LukyVj** [comment]
Fixed in #17

**Comment by LukyVj** [comment]
SO REVIEW IT <3

**Comment by Haroenv** [comment]
checked
