### ISSUE TITLE
Main branch name

### ISSUE THREAD

**Issue by dervondenbergen** [bullgit/chitchat#9]
Why is the main branch not master, which would make the most sense?
Right now it is `avatars` which sounds to me more like a feature branch.

**Comment by Haroenv** [comment]
Hm, this seems to be my fault, I think I sent a wrong PR yesterday...

**Comment by dervondenbergen** [comment]
Oh ok, if avatrars is actually the master branch then we could just rename it to master.

**Comment by Haroenv** [comment]
Yep, that's what needs to happen

**Comment by dervondenbergen** [comment]
will you do it?
